apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: leosanchezsoler/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/auth-mongo-depl.yaml
